application: daoshicha
version: 1
runtime: python
api_version: 1

handlers:
- url: /images/(.*)
  static_files: assets/images/\1
  upload: assets/images/(.*)
  secure: optional

- url: /css/(.*)
  static_files: assets/css/\1
  upload: assets/css/(.*)
  secure: optional

- url: /js/(.*)
  static_files: assets/js/\1
  upload: assets/js/(.*)
  secure: optional

- url: /javascript/(.*)
  static_files: assets/javascript/\1
  upload: assets/javascript/(.*)
  secure: optional

- url: /unittest/(.*)
  script: tests/main.py

- url: .*
  script: main.py
  secure: optional

builtins:
- appstats: on

admin_console:
  pages:
  - name: Appstats
    url: /stats
